---
deployment:
  tasks:
    - /usr/local/bin/lsphp /home/ccoditco/c-codit/backend/artisan optimize:clear
    - /usr/local/bin/lsphp /home/ccoditco/c-codit/backend/artisan optimize
    - /bin/cp -rf /home/ccoditco/c-codit/frontend/dist/. /home/ccoditco/public_html/
